#!/bin/bash
# Script to take a screenshot of whole monitor and copy it to clipboard

TMP=/tmp/screenshot.png

if [[ $# -eq 0 ]]
then
   echo "Not enough arguments"
   exit 1
fi

# Take screenshot with scrot
case $1 in
   "sel")   scrot $TMP -sz;;
   "whl")   scrot $TMP -z;;
esac

# Check if screenshot was taken
if ! [[ -e $TMP ]]
then
   notify-send "Screenshot not taken" "Please try again"
   exit 2
fi

# Copy it to clipboard via xclip
xclip -selection clipboard -t image/png -i $TMP
rm $TMP
notify-send "Screenshot taken" "Copied to clipboard" --icon=camera-photo
exit 0
