#!/bin/bash

lock() {
    betterlockscreen -l
}

select=$(echo -e "Shutdown\nReboot\nSuspend\nLock" | rofi -dmenu -i -p "Select your choice")
[ -z "$select" ] && exit 0

case "$select" in
    Lock)
        lock
        ;;
    Suspend)
        lock & systemctl suspend
        ;;
    Reboot)
        systemctl reboot
        ;;
    Shutdown)
        systemctl poweroff
        ;;
esac
